### ISSUE TITLE
display the album art + setlist/charter icon for songs on the leaderboard list, recent/hot list, and song book list to make it more easy to identify songs

### ISSUE THREAD

**Issue by RealSavageJef** [ScoreSpy/Issues#25]

**Comment by Ahriana** [comment]
i.. uh.. no? i mean i guess this is possible with the CH icons being on an API now, please dont make me do it

**Comment by Ahriana** [comment]
consider this 'good enough' for now
![image](https://user-images.githubusercontent.com/28003629/184612384-326f7752-d7a0-4cb8-ad9a-59b6371dae4e.png)
