### ISSUE TITLE
Pack-based score filtering for individual players

### ISSUE THREAD

**Issue by generalguy26** [ScoreSpy/Issues#30]
**What feature would you like to have added or changed?**

Scorehero-eque pack filtering to see scores a player has on a particular pack of songs.

**Is your feature request related to a problem? If so please describe the problem.**

Currently, selecting a player on the leaderboard for a pack of songs brings you to their profile. A player's profile (currently) has no way of filtering scores, so the only way to see which songs in a specific pack they have submitted scores for is to go to the song book for that pack and manually look through each song's leaderboard.

**Additional context**

Equivalent functionality on ScoreHero: (these scores are all for a singular player)
![image](https://user-images.githubusercontent.com/67890522/177917812-6b544f2b-1d0b-4e9d-bba9-732cfd81731f.png)

Possible UI for accessing this
![image](https://user-images.githubusercontent.com/67890522/177917364-f026fa51-6972-4bd2-8c7b-412d6e840c72.png)

**Comment by Ahriana** [comment]
that space is reserved for modifiers sadly, also their is very little space for mobile users so this isnt viable, i can add a user click tho

**Comment by Ahriana** [comment]
2nd thoughts, you can go to the user profile in the popup when you click the bar, and you can get to pack leaderboards by hitting 'song book' on the left
