### ISSUE TITLE
Djent Hero Collection needs updating

### ISSUE THREAD

**Issue by GenericMadScientist** [ScoreSpy/Issues#33]
**What feature would you like to have added or changed?**
Djent Hero Collection needs to be updated so packs 8 and 9 are tracked

**Is your feature request related to a problem? If so please describe the problem.**
They're not part of the pack LB.

**Additional context**
CSC link: https://customsongscentral.com/djent-hero-collection-packs/

**Comment by Ahriana** [comment]
updated to add packs 8 and 9, also updated icon
