### ISSUE TITLE
Incorrect Pack Icon for Anime Overchart Trackpack

### ISSUE THREAD

**Issue by generalguy26** [ScoreSpy/Issues#34]
**Describe the bug**
The setlist icon used ingame is incorrectly being used as the pack icon on the website for Anime Overchart Trackpack.

**URL of bug**
https://scorespy.online/packs/5

**Expected behavior**
Pack icon on the website should be the following screenshot.

![image](https://user-images.githubusercontent.com/67890522/178023775-c9c9d0e9-14ea-44c5-b2c5-3c8063b3437e.png)

**Comment by Ahriana** [comment]
icon updated
