### ISSUE TITLE
Sort playlists by release date rather than submission count

### ISSUE THREAD

**Issue by GenericMadScientist** [ScoreSpy/Issues#35]
**What feature would you like to have added or changed?**
For the packs page to order packs by release date (ascending or descending I don't have a strong opinion but newest releases on top makes more sense to me).

**Is your feature request related to a problem? If so please describe the problem.**
No.

**Additional context**
In [setlists.zip](https://github.com/ScoreSpy/Issues/files/9073379/setlists.zip) is the release date of every setlist tracked on the site, except The Glitter Collective which I gave a -1 due to not knowing what date to give. Rather than try to track down exact hours of release, I just used the timestamp of 00:00 GMT on the day of release. The only tie this caused is for the CSC full album packs of Circus Black, Volition, and That's the Spirit. In this case I added 1 and 2 to force the same order as they're given on the CSC website.

**Comment by Ahriana** [comment]
it is done
