### ISSUE TITLE
Removal of Drop-Down Menus for Song Difficulty

### ISSUE THREAD

**Issue by generalguy26** [ScoreSpy/Issues#36]
**What feature would you like to have added or changed?**
Clone Hero supports up to only 4 difficulties, and the screen space saved by making this a drop-down list is negligible. It would make it easier for users to see if a chart has multiple difficulties if they were explicitly listed rather than kept in a drop-down menu. 

**Additional context**
![image](https://user-images.githubusercontent.com/67890522/178063500-2469c6ff-1ca5-44d0-b9a5-e5e71795b900.png)

**Comment by Ahriana** [comment]
this would not gain any space as the side menu is still there, so this is not a change i would be looking to make unless their is a better reason for doing so
