### ISSUE TITLE
Show video cal in milliseconds rather than seconds

### ISSUE THREAD

**Issue by GenericMadScientist** [ScoreSpy/Issues#39]
**What feature would you like to have added or changed?**
Show video cal in ms instead of seconds, by multiplying by 1000.

**Is your feature request related to a problem? If so please describe the problem.**
Telling apart 0.05 and 0.005 is annoying, when it would be more convenient to see 50 and 5.

**Additional context**
None.

**Comment by Ahriana** [comment]
done
