### ISSUE TITLE
Link to pack leaderboards from song leaderboard

### ISSUE THREAD

**Issue by generalguy26** [ScoreSpy/Issues#40]
**What feature would you like to have added or changed?**
Navigation option on a song leaderboard to the pack leaderboard it is contained in. This feature already exists, but only in the song book for a pack.

**Additional context**
Button to add
![image](https://user-images.githubusercontent.com/67890522/178083763-48d3a50f-ef25-4388-a061-c6a94177093b.png)
Place to add it to
![image](https://user-images.githubusercontent.com/67890522/178083826-ffd9cb2a-331e-4eb3-9a2b-97c655cc34cd.png)

**Comment by Ahriana** [comment]
![image](https://user-images.githubusercontent.com/28003629/178196273-8fdf6297-f1d8-475e-bffb-eb9d1d6bbfa0.png)
tis done
