### ISSUE TITLE
Marathon Hero 2 DLC missing

### ISSUE THREAD

**Issue by GenericMadScientist** [ScoreSpy/Issues#44]
**Describe the bug**
The two Marathon Hero 2 DLC packs are not tracked, despite being released the same day as Marathon Hero 2 itself.

**URL of bug**
https://scorespy.online/packs/97

**To Reproduce**
1. Go to the MH2 song book.
2. Notice songs like Chaos and Owari Naki, Kono Uta are not listed.

**Expected behavior**
For the two packs to have their own LBs, ideally.

**Screenshots**
None.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Firefox
 - Version 102.0.1

**Additional context**
Note the two extra download buttons lower down on the [MH2 CSC page](https://customsongscentral.com/marathonhero2/).

**Comment by Ahriana** [comment]
added
