### ISSUE TITLE
Synergy Setlist Fixes

### ISSUE THREAD

**Issue by Desert-Stream** [ScoreSpy/Issues#54]
Frif's download contains old beta charts, the proper download link can be found here:
https://drive.google.com/file/d/1L1gYBD2Qjxa4H8mQ0DmTlm-0Q7qcPd7R/view

Additionally, if you want a description for the setlist:
"Synergy is a setlist featuring a mix of normal charts, overcharts, and customs composed by the community, mostly aimed towards top players but featuring full difficulty so everyone can enjoy"

Also the picture listed is the album art for a song called synergy, if you want you can replace it with this but idc as much
https://media.discordapp.net/attachments/992432812516966580/995065337408143521/unknown.png?width=1202&height=676

**Comment by Ahriana** [comment]
the pack has been updated locally and will be updated on the next upload cycle
