### ISSUE TITLE
Lawrence Wallace Solo Medley has wrong hash on CTH3

### ISSUE THREAD

**Issue by GenericMadScientist** [ScoreSpy/Issues#55]
**Describe the bug**
The version of Lawrence Wallace Solo Medley associated with CTH3 has hash BE938A9F23D1140865C7988D4819A0FB, but the version in the patch that should be linked is DB695337A36C0A46A3D3758F5850FA2D.

**URL of bug**
https://scorespy.online/packs/18/songs

**To Reproduce**
N/A

**Expected behavior**
Link the patched version.

**Screenshots**
N/A

**Desktop (please complete the following information):**
N/A

**Additional context**
Some songs updated in the patch are correct, so whatever the issue is it's not as simple as the patch being completely ignored. It may be the case some other songs have the same issue, but I have not done a comprehensive check.

**Comment by Ahriana** [comment]
just redownloaded CTH3 from CSC's site and 
![image](https://user-images.githubusercontent.com/28003629/180763650-29c75ec5-935a-4b08-83d9-deba7f90348d.png)

**Comment by Ahriana** [comment]
the patch is not linked on the site, so therefore it wont be correct in scorespy, its not an issue on our side

**Comment by Ahriana** [comment]
swapped for consistency sake, waiting on CSC to fix this still
