### ISSUE TITLE
Have in-game LB ordering match the website in case of ties

### ISSUE THREAD

**Issue by GenericMadScientist** [ScoreSpy/Issues#56]
**What feature would you like to have added or changed?**
In-game ties should be sorted so the oldest score takes precedence over younger scores.

**Is your feature request related to a problem? If so please describe the problem.**
It's very weird for someone to tie your score and then bop you in the in-game LB. Examples of this happening as of writing are CC bopping Hanss on [Girlfriend](https://scorespy.online/leaderboards/83BF84C0158881EF8DD69AACAD9A89B0) and Hanss bopping me on [Exile](https://scorespy.online/leaderboards/21C88ABA5B7EB95357F5EE9FEFA9C1DB?inst=0&diff=3&mods=1&min=100&max=100). The site's LBs are correct, but in-game has the ties handled the reverse way.

**Additional context**
I initially thought the issue might be using a non-stable sort but this is very unlikely to be the case because it turns out [Enumerable.OrderBy](https://docs.microsoft.com/en-us/dotnet/api/system.linq.enumerable.orderby?view=net-6.0) is stable. So the solution would either be to have the site send the game the scores in chronological order (at which point the sort being stable would do the job) or sort by a compound key (I believe tuples in C# come with lexicographical ordering so a tuple key would work).

**Comment by Ahriana** [comment]
should be resolved in the next update
