### ISSUE TITLE
Confirmation boxes behind the pause menu.

### ISSUE THREAD

**Issue by NicoBren** [ScoreSpy/Issues#58]
**Describe the bug**
Quit, Quickplay in Practice and , New Song, Quit Confirmation Box in Quickplay is sometimes rendered below the pause menu. It does not affect the usability of the confirmation menu.

**To Reproduce**
(https://cdn.discordapp.com/attachments/991009295200047145/997285740843126864/2022-07-14_18-36-47.mov)
Link in Discord of Video: https://discord.com/channels/919322196567007312/991009295200047145/997285741837172856
Tks  Quan Mower NFT???? for video. 

**Screenshots**
![image](https://user-images.githubusercontent.com/89282630/179370733-e096552c-ee6c-42b0-8dbf-d198c4b8021d.png)
![image](https://user-images.githubusercontent.com/89282630/179370829-977e30df-9545-4f87-8877-161084b59938.png)
![image](https://user-images.githubusercontent.com/89282630/179370837-7974637f-f032-4cb4-8740-ce2bc5c228ca.png)

**Comment by Ahriana** [comment]
can i have the steps in clear test please

**Comment by NicoBren** [comment]
https://streamable.com/dhha6j

Start any song > Pause > go to an option with confirmation > go back and resume the song > pause again > all confirmation boxes will be below the pause menu.

**Comment by Ahriana** [comment]
Ch side issue which is no longer applicable
