### ISSUE TITLE
Pack LBs can show 100.00% and a -1 together

### ISSUE THREAD

**Issue by GenericMadScientist** [ScoreSpy/Issues#59]
**Describe the bug**
Josch has 100.00% for S Hero as of writing despite a total of -1. Looking through his scores, he has 16 FCs and one -1.

**URL of bug**
https://scorespy.online/packs/114

**To Reproduce**
Look at the LB.

**Expected behavior**
Round down to 99.99%.

**Screenshots**
[Here](https://cdn.discordapp.com/attachments/919322196567007315/998133113672712243/unknown.png) is one by Eva, in case Josch fixes the issue with an FC or more inaccurate scores by the time you look at it.

**Additional context**
Assuming the responsible code is in JS, the way to round a percentage from 0% to 100% down to a multiple of .01% is as follows:
```js
// If 100% means a value of 1
Math.trunc(10000 * value) / 100

// If 100% means a value of 100
Math.trunc(100 * value) / 100
```
You can also use `Math.floor` instead, there is no difference for non-negative values.

**Comment by Ahriana** [comment]
implimented
