### ISSUE TITLE
Many songs in song list are the wrong song

### ISSUE THREAD

**Issue by FrostyBeep** [ScoreSpy/Issues#61]
**Describe the bug**
Many of my song.ini files are linked to the wrong folders.

**To Reproduce**
Not a clue. Happened with my initial install of ScoreSpy and remained after reinstalling.

**Expected behavior**
The song in the list would be playable. Instead, there are a bunch of songs leading to other songs

**Screenshots**
[Song List Screenshot](https://i.imgur.com/Jr13J1Z.png) - Somewhere Back in Time by Ascension appearing as the wrong song.
[Song Folder Screenshot](https://i.imgur.com/54W6l1K.png) - The song folder linked to the song. Note that song.ini is proper in that folder.
[Gameplay Clip](https://www.youtube.com/watch?v=UP3UT9WndZI) - Video showing that the song plays the wrong file.

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro
 - Version: v1.0.8

**Additional context**
I can provide any logs or other information needed. I'm starting a pastebin list of the songs and their connections just for the fun of it, and I'm finding that there are dozens of songs linked to the wrong place.

**Comment by Ahriana** [comment]
this is likely just an cache issue, delete the cache file from appdata, clear cache in the launcher drop down then start the game and re-scan
