### ISSUE TITLE
Show drum and pro drum scores with double kick modifier by default

### ISSUE THREAD

**Issue by TakaDoesStuff** [ScoreSpy/Issues#64]
**What feature would you like to have added or changed?**
When viewing a drum or pro drum leaderboard without changing any filters, enable double kick modifiers. Also, make double kick scores visible ingame when playing with no modifiers

**Is your feature request related to a problem? If so please describe the problem.**
99% of people who own a double pedal leave the modifier on 24/7, regardless of whether the song they are playing has any double kicks charted at all. Since this includes most if not all of the top players, people who don't know about this or take it into account will see drum leaderboards as unreasonably empty

**Additional context**
None

**Comment by Ahriana** [comment]
pro drums / drums will now show none and double kick by default 
![image](https://user-images.githubusercontent.com/28003629/184618487-9642d872-7996-41f5-a2a5-ab1503b85dca.png)

**Comment by Ahriana** [comment]
actually, gunna reopen this code i need to do the same in game
