### ISSUE TITLE
A way of finding unranked leaderboards using only the site

### ISSUE THREAD

**Issue by TakaDoesStuff** [ScoreSpy/Issues#68]
**What feature would you like to have added or changed?**
A way of finding unranked leaderboards using only the website, for example being able to tick an "Unranked" checkbox in the leaderboards search

**Is your feature request related to a problem? If so please describe the problem.**
The only ways to currently get to an unranked leaderboard is to know an account that recently submitted a score to it or paste the hash directly. Or to have it in your game, boot it up, find it and go to Open In ScoreSpy, which won't be viable for people who don't have the chart or are not on their main PC

**Additional context**
None

**Comment by Ahriana** [comment]
we only show charts in search we can supply a download for and dont have intention to change this. it would be a massive resource hog to index everything, especially as people can just spam create custom charts with obscene names and so on
