### ISSUE TITLE
Country leaderboards

### ISSUE THREAD

**Issue by TakaDoesStuff** [ScoreSpy/Issues#70]
**What feature would you like to have added or changed?**
Much in the same vein as global leaderboards for total score, FCs, etc. The same thing but for each individual country.

**Is your feature request related to a problem? If so please describe the problem.**
No

**Additional context**
This is a way to find other people from your country, as well as a smaller goal to reach the top of, since global top places will be out of reach for almost everybody

**Comment by Ahriana** [comment]
issue with this, and similar things especially in game is UI elements, we cant make much in the way of changes in game, and the site is due a rebuild so its hard to justify this at this time, but will leave this open as i do think its a nice feature to have

**Comment by TakaDoesStuff** [comment]
To clarify, I meant on the site only, same as the top users leaderboard

**Comment by TakaDoesStuff** [comment]
Maybe you could get there by clicking a flag
