### ISSUE TITLE
Better Error Messages

### ISSUE THREAD

**Issue by brookerose1312** [ScoreSpy/Issues#77]
**What feature would you like to have added or changed?**
Better error messages, specifically regarding error messages for profile picture upload, but also potentially other places where user-facing errors are alerted.

**Is your feature request related to a problem? If so, please describe the problem.**
It can be annoying uploading an image when just seeing "image does not match constraints", and not knowing what those constraints are beyond '500kb' is not user-friendly.

**Additional context**
I'm a FE dev, so I'm willing to help contribute if you'd let me :)

**Comment by Ahriana** [comment]
file size limit is the only constraint

**Comment by Ahriana** [comment]
accidental close
