### ISSUE TITLE
Missing translation for graphicsRestartNeeded message and not being restarted

### ISSUE THREAD

**Issue by y2k04** [ScoreSpy/Issues#78]
**Describe the bug**
The graphicsRestartNeeded message is missing a translation key and when you press okay on the dialog, it flashes the Saving the game... text at the top, but never restarts the game.

**To Reproduce**
1. Go to Settings > Video
2. Click on Graphics API
3. Select any of the items
4. Save the new settings
5. See dialog and error

**Expected behavior**
Expected to have a proper string for the message, as well as not being soft-locked by the dialog.

**Screenshots**
![image](https://user-images.githubusercontent.com/29883287/194682922-b94ff046-8f29-406d-a7cf-71b2e65fce09.png)

**Desktop (please complete the following information):**
 - OS: Windows 11 (22H2 - 22622.601)
 - ScoreSpy Version: PTB v1.4.1

**Comment by y2k04** [comment]
Happens in PTB v1.4.2 as well
![image](https://user-images.githubusercontent.com/29883287/195785933-17de6065-6397-4ae3-8631-5b11d217f20c.png)

**Comment by y2k04** [comment]
I was able to screenshot the pressing of the dialog by spamming it lmao
![image](https://user-images.githubusercontent.com/29883287/195786146-96635821-6e52-486e-9056-1cf5c87a48db.png)

**Comment by Ahriana** [comment]
this is not a scorespy issue, moreso a CH PTB one

**Comment by y2k04** [comment]
It is a ScoreSpy issue. Look at this screenshot of the most recent CH PTB:
![image](https://user-images.githubusercontent.com/29883287/195973543-d89097df-6264-47c2-a755-0cfba0022666.png)

**Comment by Ahriana** [comment]
we are not on that version

**Comment by y2k04** [comment]
Just updated to v1.5.0, it is still happening.
![image](https://user-images.githubusercontent.com/29883287/195973633-9673a27f-e8e5-4b9b-bb9f-6397bfd4f594.png)

**Comment by y2k04** [comment]
But yeah, still definitely a ScoreSpy issue, not Clone Hero.

**Comment by Ahriana** [comment]
we are still not on that version? i dont know what you want me to say, this is a CH issue from the PTB we are current using which is lagged behind upstream

**Comment by y2k04** [comment]
That makes better sense. Couldn't it be possible to update to a PTB that has this issue fixed?

**Comment by Ahriana** [comment]
its such a minor thing its not worth issuing out an update for, so no not until more content is added to make it worth doing

**Comment by y2k04** [comment]
Ok
